### ISSUE TITLE
关于七牛插件的问题

### ISSUE THREAD

**Issue by skyue** [legendtang/ghost-qiniu-heroku#1]
你好
我用的是中文版，自带的七牛插件上传图片后返回的url是md5值拼接。我希望能直接用文件名拼接，不知你这个版本是不是这样，如果是要如何使用呢（不想整体博客重新安装）。

**Comment by legendtang** [comment]
目前使用的都是“文件名-时间戳“拼接，形如 `2015/09/google-domains-1441549178372.png`，本项目使用的是 Ghost Storage API 而不是 Ghost-zh 那种改源码的方式。

需要迁移的话，导出你的内容 json，里面是包含你原有图片链接的 URL 的，如果你的文件存在于桶中这部分内容还是会正确显示的，那么直接重装并使用 https://github.com/Minwe/qn-store 提供的方法即可。

本项目是原则上是 Heroku only，如有疑问请 Reopen issue
